language: java
jdk:
  - openjdk8

branches:
  only:
    - main

# Travis CI Server's Name
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x gradlew

script: "./gradlew clean build"

# 빌드 실패 시,
after_failure:
  - if [ -f /home/travis/build/…/index.html ]; then lynx -dump /home/travis/build/…/index.html; fi

# CI 실행 완료 시 메일 알람
notifications:
  email:
    recipients:
      - poungki0823@gmail.com
