language: java
jdk:
  - openjdk8

branches:
  only:
    - main

# Travis CI Server's Name
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x gradlew

script: "./gradlew clean build --stacktrace"

before_depoly:
  - zip -r freelec-springboot2-webservice *
  - mkdir -p deploy
  - mv freelec-springboot2-webservice.zip deploy/freelec-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: freelec-springboot-build  # s3
    region: ap-northeast-2
    skip_cleanup: true
    acl: private  # zip file access : private
    local_dir: deploy  # before_deploy
    wait-until-deployed: true

# CI 실행 완료 시 메일 알람
notifications:
  email:
    recipients:
      - poungki0823@gmail.com
