spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/springboot_aws?serverTimezone=UTC&characterEncoding=UTF-8
#    username: root
#    password: 1234


  profiles:
    include: oauth, rds

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
